-- 한 FISH_NAME에 한 FISH_TYPE이라고 말한적 없다.
-- 문제에서 최종적으로 보인기준으로 그룹바이해야한다.
SELECT COUNT(*) FISH_COUNT, FISH_NAME
FROM (SELECT FISH_TYPE FROM FISH_INFO) F INNER JOIN FISH_NAME_INFO FNF ON F.FISH_TYPE = FNF.FISH_TYPE
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC;