-- 유니온써서 한번에 그룹바이해도되게ㅐㅅ따
SELECT F.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM FIRST_HALF GROUP BY FLAVOR) F 
    JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM JULY GROUP BY FLAVOR) J ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3;