-- 코드를 입력하세요
SELECT F.FLAVOR
FROM (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF) F JOIN ( SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER from JULY GROUP BY FLAVOR) J ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3;