-- 코드를 작성해주세요
# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS D 
#     JOIN
#     (SELECT * FROM SKILLCODES WHERE CATEGORY = 'Front End') S
#     ON (D.SKILL_CODE & S.CODE) = S.CODE
# ORDER BY D.ID;

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D 
JOIN SKILLCODES S 
    ON (D.SKILL_CODE & S.CODE) != 0
WHERE S.CATEGORY = 'Front End'
ORDER BY D.ID;